[accessibility]
ui_scale = 1.0000000074505806

[bar.default]
capsule_group = []
center = [ "weather", "spacer_1", "clock" ]
concave_edge_corners = true
end = [ "keyboard_layout", "bluetooth", "network", "volume", "input_volume", "brightness", "battery" ]
margin_edge = 0
margin_ends = 0
radius_bottom_left = 12
radius_bottom_right = 12
radius_top_left = 0
radius_top_right = 0
scale = 1.0000000074505806
start = [
    "session",
    "settings",
    "notifications",
    "nightlight",
    "caffeine",
    "power_profile",
    "launcher",
    "workspaces",
    "tray"
]
thickness = 35
widget_spacing = 12

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 538.0
    output = "eDP-1"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
clipboard_image_action_command = "swash --stdin --name \"swash-$(date +'%Y-%m-%d_%H:%M:%S').png\""
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true

    [shell.greeter_sync]
    auto_sync = false

    [shell.panel]
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"

    [shell.screenshot]
    copy_to_clipboard = false
    pipe_command = "swash --stdin --name \"swash-$(date +'%Y-%m-%d_%H:%M:%S').png\""
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Rosé Pine"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "kitty", "qt", "alacritty" ]

[wallpaper.default]
path = "/home/neousername/Pictures/rose-pine-greek.png"

[wallpaper.last]
path = "/home/neousername/Pictures/rose-pine-greek.png"

[wallpaper.monitors.eDP-1]
path = "/home/neousername/Pictures/rose-pine-greek.png"

[widget.clock]
color = "secondary"
format = "{:%H:%M %A %d/%m/%y}"

[widget.launcher]
color = "secondary"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
color = "secondary"

[widget.notifications]
color = "secondary"

[widget.session]
color = "error"

[widget.spacer_1]
type = "spacer"

[widget.sysmon_2]
glyph = "gpu-usage"
show_value = false
stat = "gpu_temp"
type = "sysmon"

[widget.sysmon_3]
glyph = "cpu-2"
stat = "ram_used"
type = "sysmon"

[widget.temp]
show_value = false

[widget.tray]
capsule = true
capsule_fill = "on_secondary"

[widget.volume]
color = "secondary"

[widget.workspaces]
active_pill_size = 2.5
capsule = true
capsule_fill = "on_primary"
inactive_pill_size = 1.0
pill_scale = 0.80000000000000004
show_labels = false
