# use vim keys in copy mode
setw -g mode-keys vi
bind 'v' copy-mode

# use mouse
setw -g mouse on

# terminal mode
set -g default-terminal screen-256color

# easier window switching
bind-key -n ö next-window

# show a transparent status bar without right-side metadata
set -g status on
set -g status-style 'bg=default'
set -g status-right ''

# highlight the currently active pane
set -g pane-active-border-style 'fg=green'
