# use vim keys in copy mode
setw -g mode-keys vi
bind 'v' copy-mode

# use mouse
setw -g mouse on

# terminal mode
set -g default-terminal screen-256color

# easier window switching
bind-key -n ö next-window

# disable tmux status bar completely
set -g status off
