$input_inner = rgba(00000000)
$input_outer_start = rgba(8e8e9359)
$input_outer_end = rgba(63636659)
$input_check_start = rgba(8e8e93ee)
$input_check_end = rgba(636366ee)
$input_fail = rgba(ff3b30ee)
$input_font = rgb(28, 28, 30)
$input_font_family = Inter

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $input_inner # no fill

    outer_color = $input_outer_start $input_outer_end 45deg
    check_color=$input_check_start $input_check_end 120deg
    fail_color=$input_fail $input_fail 40deg

    font_color = $input_font
    font_family = $input_font_family
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center

    placeholder_text = Input password
}
