splash = false

wallpaper {
    monitor = HDMI-A-1
    path = $HOME/Pictures/Wallpapers/
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = $HOME/Pictures/Wallpapers/
    fit_mode = cover
}
