general {
    lock_cmd = pidof hyprlock || uwsm app -- hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = pidof hyprlock || uwsm app -- hyprlock
}
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off && systemctl suspend
}
